### ISSUE TITLE
Book Loader or Context Error when loading from books

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#453]
I'm testing out loading books via context and am running into an error that I suspect has to do with having an empty metadata list in context. 

My context file is just:
```
obsfiledb: 'obsfiledb.sqlite'
obsdb: 'obsdb.sqlite'

imports:
    - sotodlib.io.load
    - sotodlib.io.load_book
    - sotodlib.io.metadata

obs_loader_type: 'obs-book'
```

And when I try to load an axis manager I'm getting this error:
```
>>> aman = context.get_obs(obs, dets=list(dets))
WARNING: sotodlib.core.context: Key "metadata" not present in context.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kmharrin/.local/lib/python3.10/site-packages/sotodlib/core/context.py", line 302, in get_obs
    aman.merge(meta)
  File "/home/kmharrin/.local/lib/python3.10/site-packages/sotodlib/core/axisman.py", line 800, in merge
    raise ValueError(f'Key conflict: more than one merge target '
ValueError: Key conflict: more than one merge target shares keys: {'det_info'}
```

**Comment by kmharrington** [comment]
closed now
